program: train_sweep.py
method: grid
project: summarization_sweep
name: kobart_baseline_sweep
metric:
  goal: maximize
  name: eval/rouge1
parameters:
  model_name:
    values: [gogamza/kobart-base-v2]
  batch_size:
    values: [32]  # gradient_accumulation_steps = 2
  epochs:
    values: [15]
  label_smoothing_factor:
    values: [0.1, 0.2, 0.3]
  weight_decay:
    values: [0.01, 0.05, 0.1]